# Canada - Calgary
module "ca-west-1" {
  source = "./modules/agent"

  region                    = "ca-west-1"
  agent_create              = var.agent_create
  agent_name                = var.agent_name
  agent_watcher             = var.agent_watcher
  agent_logs                = var.agent_logs
  agent_metrics             = var.agent_metrics
  agent_logs_retention      = var.agent_logs_retention
  agent_p2p_archivist_ports = var.agent_p2p_archivist_ports
  agent_p2p_ipfs_ports      = var.agent_p2p_ipfs_ports
  agent_p2p_radicle_ports   = var.agent_p2p_radicle_ports
  agent_p2p_ton_ports       = var.agent_p2p_ton_ports
  agent_p2p_torrent_ports   = var.agent_p2p_torrent_ports
  agent_custom_ports        = var.agent_custom_ports
  default_tags              = var.default_tags
  cidr_block                = var.cidr_block
  az_number                 = var.az_number
  allow_ssh                 = var.allow_ssh
  public_keys               = local.public_keys
  os_name                   = var.os_name
  instance_type             = var.instance_type
  volume_size               = var.volume_size
  volume_type               = var.volume_type
  volume_iops               = var.volume_iops
  volume_throughput         = var.volume_throughput
  initial_deploy            = var.initial_deploy
  desired_capacity          = var.desired_capacity
  start_time                = var.start_time
  start_offset              = var.start_offset
  run_duration              = var.run_duration
  time_offset_version       = var.time_offset_version
  agent_cron_schedule       = var.agent_cron_schedule
  agent_commands            = var.agent_commands
  agent_commands_defaults   = var.agent_commands_defaults
  agent_cc_hosts            = local.agent_cc_hosts
  agent_cc_commands         = var.agent_cc_commands
  agent_cc_commands_prefix  = var.agent_cc_commands_prefix
  agent_repository_ssh_key  = local.agent_repository_ssh_key
  watcher_name              = var.watcher_name
  scheduler_name            = var.scheduler_name
  scheduler_expression      = var.scheduler_expression
  lambda_architecture       = var.lambda_architecture
}
