# Common - Get cloud
- name: Identify cloud
  ansible.builtin.shell: |
    cloud=$(curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/vendor/labels/cloud/)
    if [[ "${cloud}" == "yandex" ]]; then
      echo "${cloud}"
    else
      cloud-init query cloud-name
    fi
  args:
    executable: bash
  register: common_cloud
  changed_when: false

- name: Compute variables
  ansible.builtin.set_fact:
    common_cloud: >-
      {% if common_cloud.stdout == 'gce' -%}
        gcp
      {%- elif common_cloud.stdout == 'oracle' -%}
        oci
      {%- elif common_cloud.stdout != '' -%}
        {{ common_cloud.stdout }}
      {%- else -%}
        unknown-cloud
      {%- endif %}
