# Common - Get region
- name: Identify region
  ansible.builtin.shell: |
    set -o pipefail
    case {{ common_cloud }} in
      aliyun)       cloud-init query ds.meta-data.region-id                                 ;;
      digitalocean) curl -s http://169.254.169.254/metadata/v1/region                       ;;
      exoscale)     curl -s http://169.254.169.254/1.0/meta-data/availability-zone          ;;
      hetzner)      curl -s http://169.254.169.254/hetzner/v1/metadata/availability-zone    ;;
      oci)          cloud-init query ds.region                                              ;;
      scaleway)     curl -s http://169.254.42.42/conf | awk -F '=' '/^ZONE/ {print $2}'     ;;
      upcloud)      curl -s http://169.254.169.254/metadata/v1/region                       ;;
      yandex)       curl -s -H "Metadata-Flavor: Google" \
                      http://169.254.169.254/computeMetadata/v1/instance/vendor/environment ;;
      *)            cloud-init query region                                                 ;;
    esac
  args:
    executable: bash
  register: common_region
  changed_when: false

- name: Compute variables
  ansible.builtin.set_fact:
    common_region: '{{ common_region.stdout }}'
