services:
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=vertamedia-clickhouse-datasource
    ports:
      - 3000:3000
    volumes:
      - '$PWD/grafana_data:/var/lib/grafana'
