# AWS - Management
- name: Check for AWS CLI
  ansible.builtin.command: which aws
  register: watcher_aws_cli
  changed_when: false
  failed_when: false

- name: Install zip
  ansible.builtin.apt:
    name: zip
    state: present
  when: watcher_aws_cli.stdout == ''

- name: Download AWS CLI
  ansible.builtin.get_url:
    url: '{{ watcher_aws_cli_url }}'
    dest: '{{ temp_folder }}/{{ watcher_aws_cli_archive }}'
    mode: '644'
  when: watcher_aws_cli.stdout == ''

- name: Unarchive AWS CLI
  ansible.builtin.unarchive:
    src: '{{ temp_folder }}/{{ watcher_aws_cli_archive }}'
    dest: '{{ temp_folder }}'
  when: watcher_aws_cli.stdout == ''

- name: Install AWS CLI
  ansible.builtin.shell: '{{ temp_folder }}/aws/install'
  args:
    executable: bash
  changed_when: false
  when: watcher_aws_cli.stdout == ''

- name: Update autoscaler
  ansible.builtin.shell: |
    set -o pipefail

    # Variables
    desired_capacity_cc={{ watcher_desired_capacity }}
    stop_scheduler="initial-stop"
    diff_time_admissible=60

    # Get metadata
    token=$(curl -X PUT -s http://169.254.169.254/latest/api/token -H "X-aws-ec2-metadata-token-ttl-seconds: 180")
    role=$(curl -s -H "X-aws-ec2-metadata-token: ${token}" http://169.254.169.254/latest/meta-data/iam/security-credentials)
    credentials=$(curl -s -H "X-aws-ec2-metadata-token: ${token}" http://169.254.169.254/latest/meta-data/iam/security-credentials/$role)
    region=$(curl -s -H "X-aws-ec2-metadata-token: ${token}" http://169.254.169.254/latest/meta-data/placement/region)
    asg_name=$(curl -s -H "X-aws-ec2-metadata-token: ${token}" http://169.254.169.254/latest/meta-data/tags/instance/aws:autoscaling:groupName)

    # Authenticate
    export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' <<< "${credentials}")
    export AWS_SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' <<< "${credentials}")
    export AWS_SESSION_TOKEN=$(jq -r '.Token' <<< "${credentials}")

    # Check if scaling is required
    desired_capacity_current=$(aws autoscaling describe-auto-scaling-groups \
      --region "${region}" \
      --auto-scaling-group-name "${asg_name}" \
      --query 'AutoScalingGroups[0].DesiredCapacity')

    scaling_drift="${desired_capacity_current} --> ${desired_capacity_cc}"

    if [[ -n "${desired_capacity_current}" ]]; then
      if [[ ${desired_capacity_current} -eq ${desired_capacity_cc} ]]; then
        echo "Skip scaling agent instances: ${scaling_drift}"
        exit 0
      fi
    fi

    # Get stop scheduler
    scheduler_time_asg=$(aws autoscaling describe-scheduled-actions \
      --region "${region}" \
      --auto-scaling-group-name "${asg_name}" \
      --query 'ScheduledUpdateGroupActions[?ScheduledActionName==`'${stop_scheduler}'`].StartTime' \
      --output=text)

    # Check stop scheduler and current time diff
    if [[ -n "${scheduler_time_asg}" ]]; then
      scheduler_time=$(date -d "${scheduler_time_asg}" "+%s")
      current_time=$(date "+%s")
      diff_time=$((scheduler_time - current_time))

      # Skip update when near the stop
      if [[ "${diff_time}" -lt "${diff_time_admissible}" ]]; then
        echo "Skip scaling agent instances - stop diff_time ${diff_time} is lower than ${diff_time_admissible}"
        exit 0
      else
        echo "Scaling agent instances will be performed - stop diff_time is $(date -d @${diff_time} +%T)"
      fi
    fi

    # Update autoscaler
    aws autoscaling update-auto-scaling-group \
      --region "${region}" \
      --auto-scaling-group-name "${asg_name}" \
      --desired-capacity "${desired_capacity_cc}"

    # Check scaling status
    if [[ $? -eq 0 ]]; then
      echo "Scaling agent instances successful: ${scaling_drift}"
    else
      echo "Scaling agent instances failed: ${scaling_drift}"
    fi
  args:
    executable: bash
  register: watcher_autoscaler
  changed_when: false

- name: Show autoscaler output
  ansible.builtin.debug:
    msg: |
      {{ item }}:
      {% for out in item | extract(watcher_autoscaler) %}
      {{ out }}
      {% endfor %}
  loop:
    - stdout_lines
    - stderr_lines
