# GCP - Management
- name: Check for Google Cloud CLI
  ansible.builtin.command: which gcloud
  register: watcher_gcloud_cli
  changed_when: false
  failed_when: false

- name: Install Google Cloud CLI prerequisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
  when: watcher_gcloud_cli.stdout == ''

- name: Add Google Cloud CLI repository key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/cloud.google.gpg
    mode: '644'
  when: watcher_gcloud_cli.stdout == ''

- name: Add Google Cloud CLI repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk.list
  when: watcher_gcloud_cli.stdout == ''

- name: Install Google Cloud CLI
  ansible.builtin.apt:
    name: google-cloud-cli
    update_cache: true
  when: watcher_gcloud_cli.stdout == ''

- name: Update autoscaler
  ansible.builtin.shell: |
    set -o pipefail

    # Variables
    desired_capacity_cc={{ watcher_desired_capacity }}

    # Get metadata
    project_id=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/project/project-id)
    region=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/zone | xargs basename | sed 's/-[a-z]$//')
    instance_group=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/created-by | xargs basename)

    # Check if scaling is required
    desired_capacity_current=$(gcloud compute instance-groups managed \
      describe "${instance_group}" \
      --region="${region}" \
      --format="get(autoscaler.autoscalingPolicy.maxNumReplicas)")

    scaling_drift="${desired_capacity_current} --> ${desired_capacity_cc}"

    if [[ -n "${desired_capacity_current}" ]]; then
      if [[ ${desired_capacity_current} -eq ${desired_capacity_cc} ]]; then
        echo "Skip scaling agent instances: ${scaling_drift}"
        exit 0
      fi
    fi

    # Check for schedule
    schedule=$(gcloud compute instance-groups managed \
      describe "${instance_group}" \
      --region="${region}" \
      --format="json" \
      | jq -r '.autoscaler.autoscalingPolicy.scalingSchedules // [] | keys[]')

    # Update schedule
    if [[ -n "${schedule}" ]]; then
      gcloud compute instance-groups managed \
        update-autoscaling "${instance_group}" \
        --region="${region}" \
        --update-schedule="${schedule}" \
        --schedule-min-required-replicas="${desired_capacity_cc}"
    else
      update_autoscaling_arg="--min-num-replicas=${desired_capacity_cc}"
    fi

    # Update autoscaler
    gcloud compute instance-groups managed \
      update-autoscaling "${instance_group}" \
      --region="${region}" \
      --max-num-replicas="${desired_capacity_cc}" ${update_autoscaling_arg}

    # Check scaling status
    if [[ $? -eq 0 ]]; then
      echo "Scaling agent instances successful: ${scaling_drift}"
    else
      echo "Scaling agent instances failed: ${scaling_drift}"
    fi
  args:
    executable: bash
  register: watcher_autoscaler
  changed_when: false

- name: Show autoscaler output
  ansible.builtin.debug:
    msg: |
      {{ item }}:
      {% for out in item | extract(watcher_autoscaler) %}
      {{ out }}
      {% endfor %}
  loop:
    - stdout_lines
    - stderr_lines
