# Radicle - Variables
---
radicle_name:           radicle
radicle_folder:         '{{ base_folder }}/{{ radicle_name }}'
radicle_user:           '{{ radicle_name }}'
radicle_install_folder: /usr/local/bin
radicle_bin:            radicle-node
radicle_binaries:       'git-remote-rad rad {{ radicle_bin }}'
radicle_version:        1.5.0 # https://radicle.xyz/download
radicle_archive:        '{{ radicle_name }}-{{ radicle_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.xz'
radicle_archive_folder: '{{ temp_folder }}/{{ radicle_archive | splitext | first | splitext | first }}'
radicle_url:            'https://files.radicle.xyz/releases/{{ radicle_version }}/{{ radicle_archive }}'
radicle_checksum_url:   '{{ radicle_url }}.sha256'
radicle_tcp_port:       8776
radicle_config_file:    config.json
radicle_service_name:   '{{ radicle_name }}'
radicle_node_alias:     '' # seeder
radicle_seed_timeout:   300
radicle_rid:            ''
radicle_enabled:        true
radicle_update:         false
