# Archivist - Management
- name: Wait app
  ansible.builtin.include_tasks:
    file: wait.yml

- name: Get existing cid
  ansible.builtin.uri:
    url: '{{ archivist_api_endpoint }}/data'
  register: archivist_existing_cid

- name: Pin cid
  ansible.builtin.shell: timeout {{ archivist_pin_timeout }} curl -s {{ archivist_api_endpoint }}/data/{{ item }}/network/stream &
  loop: '{{ archivist_cid | split }}'
  changed_when: false
  when: item not in (archivist_existing_cid.json | json_query('content[*].cid') | join)

- name: Get existing cid latest
  ansible.builtin.uri:
    url: '{{ archivist_api_endpoint }}/data'
  register: archivist_existing_cid_latest

- name: Show cid latest
  ansible.builtin.debug:
    msg: |
      {% for item in archivist_existing_cid_latest.json | json_query('content[*].[cid, manifest.uploadedAt]') %}
      {{ item[0] }} - {{ '%Y-%m-%d %H:%M:%S' | strftime(item[1], utc=true) }}
      {% endfor %}
